version: '3'

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - deployment

networks:
  deployment:
    driver: bridge
